### ISSUE TITLE
Issue when training the model

### ISSUE THREAD

**Issue by antoinehabis** [DeepTrial/SG-One-pytorch#1]
Hello!

Thank you very much for your implementation!
 I ran into some issue using the train_frame.py do you have any idea why?

Running parameters:

{
    "arch":"sg_one",
    "max_steps":1000000,
    "lr":1e-05,
    "disp_interval":200,
    "save_interval":10000,
    "snapshot_dir":"/home/ahabis/SG-One-pytorch/snapshots",
    "resume":false,
    "batch_size":1,
    "start_count":0,
    "split":"train",
    "group":0,
    "num_folds":4,
    "dataset_name":"voc_2012"
}
/home/ahabis/miniconda3/envs/SGONE/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/ahabis/miniconda3/envs/SGONE/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Number of Parameters: 18992194
group,num_folds 0 4
Grab the dataset: voc_2012_train
read file 'aaai_pascal_voc_seg_img_db.pkl' successful!
Total images after filtering: 0
Train Categories: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Val Categories: [0, 1, 2, 3, 4]
Total images: 1464
Traceback (most recent call last):
  File "/home/ahabis/SG-One-pytorch/train_frame.py", line 128, in <module>
    train(args)
  File "/home/ahabis/SG-One-pytorch/train_frame.py", line 75, in train
    for dataPacket in train_loader:
  File "/home/ahabis/miniconda3/envs/SGONE/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/ahabis/miniconda3/envs/SGONE/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/ahabis/miniconda3/envs/SGONE/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/ahabis/miniconda3/envs/SGONE/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ahabis/miniconda3/envs/SGONE/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ahabis/miniconda3/envs/SGONE/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ahabis/miniconda3/envs/SGONE/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ahabis/SG-One-pytorch/datasets/parse_dataset.py", line 64, in __getitem__
    dat_dicts = self.img_db.get_triple_images(split='train', group=self.group, num_folds=4)
  File "/home/ahabis/SG-One-pytorch/datasets/Imdb.py", line 107, in get_triple_images
    sample_img_ids_1 = np.random.choice(len(self.grouped_imgs[rand_cat[0]]), 2, replace=False)
  File "mtrand.pyx", line 944, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

**Comment by antoinehabis** [comment]
Issue solved:
The .pkl file doesn't contains the labels.
I deleted the pkl file so that the code doesn't find it and generate it.
Labels are generated according to the colors on the images.
Hpwever, images are in RGBA and the colormap in RGB.
To solve the issue just  replace
```
def get_labels(self, mask_path):
        mask = self.read_mask(mask_path) 
        height,width=mask.shape[:2]
        labels=[]
        for hi in range(height):                #according the color of every pixel to determine the categories 
            for wj in range(width): 
                temp=(mask[hi,wj]*256).astype(np.uint8).tolist()
                for l in range(20):
                    if operator.eq(temp,self.color_map[l]):
                        labels.append(l)
        labels=np.unique(labels).tolist()
```
to 
```
def get_labels(self, mask_path):
        mask = self.read_mask(mask_path) 
        height,width=mask.shape[:2]
        labels=[]
        for hi in range(height):                #according the color of every pixel to determine the categories 
            for wj in range(width): 
                temp=(mask[hi,wj]*256).astype(np.uint8).tolist()
                for l in range(20):
                    if operator.eq(temp[:-1],self.color_map[l]):
                        labels.append(l)
        labels=np.unique(labels).tolist()
```

in pascal_voc_seg
